# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/project_3_main/TE0726.xdc

# Block Designs: bd/FullBuild/FullBuild.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild || ORIG_REF_NAME==FullBuild} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_i2c_user_logic_ADC_0_0/FullBuild_i2c_user_logic_ADC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_i2c_user_logic_ADC_0_0 || ORIG_REF_NAME==FullBuild_i2c_user_logic_ADC_0_0} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_i2c_user_logic_LCD_0_0/FullBuild_i2c_user_logic_LCD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_i2c_user_logic_LCD_0_0 || ORIG_REF_NAME==FullBuild_i2c_user_logic_LCD_0_0} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_PWM_gen_0_0/FullBuild_PWM_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_PWM_gen_0_0 || ORIG_REF_NAME==FullBuild_PWM_gen_0_0} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_Reset_Delay_0_0/FullBuild_Reset_Delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_Reset_Delay_0_0 || ORIG_REF_NAME==FullBuild_Reset_Delay_0_0} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_statemachine_0_0/FullBuild_statemachine_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_statemachine_0_0 || ORIG_REF_NAME==FullBuild_statemachine_0_0} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_btn_debounce_toggle_0_0/FullBuild_btn_debounce_toggle_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_btn_debounce_toggle_0_0 || ORIG_REF_NAME==FullBuild_btn_debounce_toggle_0_0} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_btn_debounce_toggle_0_1/FullBuild_btn_debounce_toggle_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_btn_debounce_toggle_0_1 || ORIG_REF_NAME==FullBuild_btn_debounce_toggle_0_1} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_util_vector_logic_0_0/FullBuild_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_util_vector_logic_0_0 || ORIG_REF_NAME==FullBuild_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_xlconstant_0_0/FullBuild_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_xlconstant_0_0 || ORIG_REF_NAME==FullBuild_xlconstant_0_0} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_processing_system7_0_0/FullBuild_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_processing_system7_0_0 || ORIG_REF_NAME==FullBuild_processing_system7_0_0} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_LCD_Controller_0_0/FullBuild_LCD_Controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_LCD_Controller_0_0 || ORIG_REF_NAME==FullBuild_LCD_Controller_0_0} -quiet] -quiet

# IP: bd/FullBuild/ip/FullBuild_LCD_Data_Cutter_0_0/FullBuild_LCD_Data_Cutter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullBuild_LCD_Data_Cutter_0_0 || ORIG_REF_NAME==FullBuild_LCD_Data_Cutter_0_0} -quiet] -quiet

# XDC: bd/FullBuild/ip/FullBuild_processing_system7_0_0/FullBuild_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FullBuild_processing_system7_0_0 || ORIG_REF_NAME==FullBuild_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/FullBuild/FullBuild_ooc.xdc
