# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7z010clg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.cache/wt [current_project]
set_property parent.project_path C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part trenz.biz:te0726_10_1c:part0:2.1 [current_project]
set_property ip_output_repo c:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/imports/project_3_main/i2c_master.vhd
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/imports/project_3_main/i2c_user_logic_ADC.vhd
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/imports/project_3_main/i2c_user_logic_LCD.vhd
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/imports/project_3_main/PWM_Gen.vhd
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/imports/project_3_main/reset_delay.vhd
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/imports/project_3_main/Statemachine.vhd
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/imports/project_3_main/btn_debounce_toggle.vhd
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/LCD_Controller.vhd
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/LCD_Data_Cutter.vhd
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/imports/project_3_main/clock_gen.vhd
  C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/bd/FullBuild/hdl/FullBuild_wrapper.vhd
}
add_files C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/bd/FullBuild/FullBuild.bd
set_property used_in_implementation false [get_files -all c:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/bd/FullBuild/ip/FullBuild_processing_system7_0_0/FullBuild_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/sources_1/bd/FullBuild/FullBuild_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/constrs_1/imports/project_3_main/TE0726.xdc
set_property used_in_implementation false [get_files C:/Users/nathani/Documents/GitHub/EE316_2025/Project3/project_3_main/project_3_main.srcs/constrs_1/imports/project_3_main/TE0726.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FullBuild_wrapper -part xc7z010clg225-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FullBuild_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FullBuild_wrapper_utilization_synth.rpt -pb FullBuild_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
