@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Mar 11 23:38:28 -0400 2025
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto c83ba13c319d4714a47426d321815e3d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot uart_tb_behav xil_defaultlib.uart_tb -log elaborate.log"
call xelab  -wto c83ba13c319d4714a47426d321815e3d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot uart_tb_behav xil_defaultlib.uart_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
