# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z007sclg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir U:/EE316/Project5/LCD_StateMachine/LCD_StateMachine.cache/wt [current_project]
set_property parent.project_path U:/EE316/Project5/LCD_StateMachine/LCD_StateMachine.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:cora-z7-07s:part0:1.1 [current_project]
set_property ip_output_repo u:/EE316/Project5/LCD_StateMachine/LCD_StateMachine.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  U:/EE316/Project5/LCD_StateMachine/I2C_userlogic.vhd
  U:/EE316/Project5/LCD_StateMachine/btn_debounce_toggle.vhd
  U:/EE316/Project5/LCD_StateMachine/clk_enabler.vhd
  U:/EE316/Project5/LCD_StateMachine/debounce.vhd
  U:/EE316/Project5/LCD_StateMachine/i2c_manager.vhd
  U:/EE316/Project5/LCD_StateMachine/ps2_keyboard.vhd
  U:/EE316/Project5/LCD_StateMachine/ps2_keyboard_to_ascii.vhd
  U:/EE316/Project5/LCD_StateMachine/reset_delay.vhd
  U:/EE316/Project5/LCD_StateMachine/rotary.vhd
  U:/EE316/Project5/LCD_StateMachine/shift_register.vhd
  U:/EE316/Project5/LCD_StateMachine/state_machine.vhd
  U:/EE316/Project5/LCD_StateMachine/uart.vhd
  U:/EE316/Project5/LCD_StateMachine/LCD_StateMachine.srcs/sources_1/new/top_level.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc U:/EE316/Project5/Cora-Z7-07S-Master.xdc
set_property used_in_implementation false [get_files U:/EE316/Project5/Cora-Z7-07S-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xc7z007sclg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
