webtalk_init -webtalk_dir C:/Users/uonml/Documents/GitHub/EE316_2025/Project4/keyboard/uart2/uart2.sim/sim_1/behav/xsim/xsim.dir/tb_user_uart_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 12 20:33:12 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "175495545_1777507777_210710067_747" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "739fbed5-8b61-4d88-9c21-322e30cd98df" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1e2aa96430944368acd122ecd8f1f952" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "42" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3312 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6608_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1986002817 -regid "175495545_1777507777_210710067_747" -xml C:/Users/uonml/Documents/GitHub/EE316_2025/Project4/keyboard/uart2/uart2.sim/sim_1/behav/xsim/xsim.dir/tb_user_uart_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/uonml/Documents/GitHub/EE316_2025/Project4/keyboard/uart2/uart2.sim/sim_1/behav/xsim/xsim.dir/tb_user_uart_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/uonml/Documents/GitHub/EE316_2025/Project4/keyboard/uart2/uart2.sim/sim_1/behav/xsim/xsim.dir/tb_user_uart_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
