# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Cora-Z7-07S-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps2_keyboard_to_ascii_0_1/design_1_ps2_keyboard_to_ascii_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps2_keyboard_to_ascii_0_1 || ORIG_REF_NAME==design_1_ps2_keyboard_to_ascii_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_user_logic_uart_0_1/design_1_user_logic_uart_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_user_logic_uart_0_1 || ORIG_REF_NAME==design_1_user_logic_uart_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Reset_Delay_0_0/design_1_Reset_Delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Reset_Delay_0_0 || ORIG_REF_NAME==design_1_Reset_Delay_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_baud_rate_0_0/design_1_baud_rate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_baud_rate_0_0 || ORIG_REF_NAME==design_1_baud_rate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_btn_debounce_toggle_0_0/design_1_btn_debounce_toggle_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_btn_debounce_toggle_0_0 || ORIG_REF_NAME==design_1_btn_debounce_toggle_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
